/*
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

#ifndef ENGINE_CHECK_H
#define ENGINE_CHECK_H

#include <pthread.h>

#define KAE_QUEUE_CHECKING_INTERVAL 15000


struct kae_check_q_task_s {
	int             init_flag;
	int             exit_flag;
	pthread_t       thread_id;
};

typedef struct kae_check_q_task_s KAE_CHECK_Q_TASK;

void kae_enable_async(void);
void kae_disable_async(void);
int  kae_is_async_enabled(void);
int  kae_checking_q_thread_init(void);
void kae_check_thread_reset(void);
void kae_checking_q_sync_destroy(void);

enum HISI_FUNC_CODE {
	KAE_F_HPRE_GET_RSA_METHODS = 100,
	KAE_F_CHANGRSAMETHOD,
	KAE_F_HPRE_PKEY_METHS,
	KAE_F_BIND_HELPER,
	KAE_F_RSA_FILL_KENGEN_PARAM,
	KAE_F_HPRE_RSA_PUBENC,
	KAE_F_HPRE_RSA_PRIENC,
	KAE_F_HPRE_RSA_PUBDEC,
	KAE_F_HPRE_RSA_PRIDEC,
	KAE_F_HPRE_RSA_PRIMEGEN,
	KAE_F_HPRE_RSA_KEYGEN,
	KAE_F_CHECK_PUBKEY_PARAM,
	KAE_F_HPRE_PUBENC_PADDING,
	KAE_F_HPRE_PRIENC_PADDING,
	KAE_F_CHECK_HPRE_PUBDEC_PADDING,
	KAE_F_CHECK_HPRE_PRIDEC_PADDING,
	KAE_F_SEC_SM3_INIT,
	KAE_F_SEC_SM3_FINAL,
	KAE_F_DIGEST_SOFT_INIT,
	KAE_F_ENGINE_WD,
	KAE_F_BIND_FN,
	KAE_F_CHECK_DATA_VALID,
	KAE_F_CHECK_MALLOC_SUCC,
	KAE_F_HPRE_GET_DH_METHODS,
	KAE_F_HPRE_DH_KEYGEN,
	KAE_F_HPRE_DH_KEYCOMP,
	KAE_F_CHANGDHMETHOD
};

enum HISI_RESON_CODE {
	KAE_R_NO_MATCH_DEVICE = 100,
	KAE_R_MALLOC_FAILURE,
	KAE_R_HWMEM_MALLOC_FAILURE,
	KAE_R_INPUT_PARAM_ERR,
	KAE_R_SET_ID_FAILURE,
	KAE_R_SET_NAME_FAILURE,
	KAE_R_SET_PKEYMETH_FAILURE,
	KAE_R_SET_RSA_FAILURE,
	KAE_R_SET_DESTORY_FAILURE,
	KAE_R_SET_INIT_FAILURE,
	KAE_R_SET_CTRL_FAILURE,
	KAE_R_SET_CMDDEF_FAILURE,
	KAE_R_SET_FINISH_FAILURE,
	KAE_R_UNSUPPORT_HARDWARE_TYPE,
	KAE_R_TIMEOUT,
	KAE_R_RSARECV_FAILURE,
	KAE_R_RSARECV_STATE_FAILURE,
	KAE_R_RSASEND_FAILURE,
	KAE_R_GET_ALLOCED_HWMEM_FAILURE,
	KAE_R_FREE_ALLOCED_HWMEM_FAILURE,
	KAE_R_RSA_KEY_NOT_COMPELET,
	KAE_R_RSA_PADDING_FAILURE,
	KAE_R_DATA_TOO_LARGE_FOR_MODULUS,
	KAE_R_DATA_GREATER_THEN_MOD_LEN,
	KAE_R_CHECKPADDING_FAILURE,
	KAE_R_ERR_LIB_BN,
	KAE_R_RSA_KEY_SIZE_TOO_SMALL,
	KAE_R_MODULE_TOO_LARGE,
	KAE_R_INVAILED_E_VALUE,
	KAE_R_UNKNOW_PADDING_TYPE,
	KAE_R_INPUT_FIKE_LENGTH_ZERO,
	KAE_R_SET_CIPHERS_FAILURE,
	KAE_R_SET_DIGESTS_FAILURE,
	KAE_R_NEW_ENGINE_FAILURE,
	KAE_R_BIND_ENGINE_FAILURE,
	KAE_R_RSA_SET_METHODS_FAILURE,
	KAE_R_PUBLIC_KEY_INVALID,
	KAE_R_PUBLIC_ENCRYPTO_FAILURE,
	KAE_R_PUBLIC_DECRYPTO_FAILURE,
	KAE_R_GET_PRIMEKEY_FAILURE,
	KAE_R_DH_SET_METHODS_FAILURE,
	KAE_R_SET_DH_FAILURE,
	KAE_R_DH_KEY_SIZE_TOO_LARGE,
	KAE_R_DH_INVALID_PARAMETER,
	KAE_R_ENGINE_ALREADY_DEFINED,
};
extern void *kae_memcpy(void *dstpp, const void *srcpp, size_t len);
int get_dev_by_sync_mode(int inlen);
#endif // end of ENGINE_CHECK_H

